spring.application.name=SpringSecurity
#spring.application.name=Hospital-Management-System

spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=S@lman255244

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=mysql
server.port=7070
#management.endpoints.web.exposure.include=health,info,metrics
#management.endpoint.health.show-details=always
spring.jpa.defer.datasource.initialization=true
#//spring.sql.init.mode=always
#//spring.sql.init.data.locations=classpath:data.sql
#Turn off the Spring Boot banner
spring.main.banner-mode=off
#server.servlet.context.path=/api/v1
#security config
spring.security.user.name=salman
spring.security.user.password=salman2552
